services:
  deliverytrack:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./:/app
    command: >
      sh -c "
        npm install &&
        npm run build &&
        npm start
      "
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - deliverytrack-network

networks:
  deliverytrack-network:
    driver: bridge
