services:
  deliverytrack:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/app
    command: >
      sh -c "
        apk add --no-cache git &&
        npm install &&
        npm run dev
      "
    restart: unless-stopped
    networks:
      - deliverytrack-network

networks:
  deliverytrack-network:
    driver: bridge
